local mounts = {
    -- Config

    dollID = 50008, -- Change this to your dolls or items, item ID

    -- Main Window Messages (The first window the player sees)
    mainTitle = "Escoje una montura!",
    mainMsg = "Elige una montura para desbloquear.",

    -- Already Owned Window (The window that appears when the player already owns the addon)
    ownedTitle = "Whoops!",
    ownedMsg = "Ya tienes esta montura. Elige otra.",

    -- No Doll in Backpack (The window that appears when the player doesnt have the doll in their backpack)
    dollTitle = "Whoops!",
    dollMsg = "El exclusive mount doll debe estar en tu mochila.",
    -- End Config

    -- Mounts Table
    -- Unicorn Group
    [114] = { name = "Arctic Unicorn", ID = 114 },
    [113] = { name = "Blazing Unicorn", ID = 113 },
    [115] = { name = "Prismatic unicorn", ID = 115 },

    -- Horse Group
    [23] = { name = "Armoured War Horse", ID = 23 },
    [204] = { name = "Jousting Horse", ID = 204 },
    [203] = { name = "Parade Horse", ID = 203 },
    [22] = { name = "Rented Horse", ID = 22 },
    [26] = { name = "Rented Horse (Brown)", ID = 26 },
    [25] = { name = "Rented Horse (Gray)", ID = 25 },
    [205] = { name = "Tourney Horse", ID = 205 },

    -- Azudocus Group
    [44] = { name = "Azudocus", ID = 44 },
    [45] = { name = "Carpacosaurus", ID = 45 },

    -- Batcat Group
    [77] = { name = "Batcat", ID = 77 },
    [75] = { name = "Flitterkatzen", ID = 75 },
    [76] = { name = "Venompaw", ID = 76 },

    -- Tombstinger Group
    [46] = { name = "Death Crawler", ID = 46 },
    [49] = { name = "Jade Pincer", ID = 49 },
    [21] = { name = "Scorpion King", ID = 21 },
    [36] = { name = "Tombstinger", ID = 36 },

    -- Black Sheep Group
    [4] = { name = "Black Sheep", ID = 4 },

    -- Ungrouped Mounts
    [163] = { name = "Antelope", ID = 163 },
    [153] = { name = "Battle Badger", ID = 153 },
    [73] = { name = "Black Stag", ID = 73 },
    [58] = { name = "Blackpelt", ID = 58 },
    [9] = { name = "Blazebringer", ID = 9 },
    [92] = { name = "Bloodcurl", ID = 92 },
    [156] = { name = "Blue Rolling Barrel", ID = 156 },
    [229] = { name = "Bog Tyrant", ID = 229 },
    [189] = { name = "Bogwurm", ID = 189 },
    [213] = { name = "Boisterous Bull", ID = 213 },
    [129] = { name = "Boreal Owl", ID = 129 },
    [208] = { name = "Brass Speckled Koi", ID = 208 },
    [133] = { name = "Bright Percht Sleigh", ID = 133 },
    [151] = { name = "Bright Percht Sleigh Final", ID = 151 },
    [148] = { name = "Bright Percht Sleigh Variant", ID = 148 },
    [231] = { name = "Bumblebee", ID = 231 },
    [139] = { name = "Bunny Dray", ID = 139 },
    [137] = { name = "Caped Snowman", ID = 137 },
    [117] = { name = "Cave Tarantula", ID = 117 },
    [146] = { name = "Cerberus Champion", ID = 146 },
    [90] = { name = "Cinderhoof", ID = 90 },
    [200] = { name = "Cinnamon ibex", ID = 200 },
    [132] = { name = "Cold Percht Sleigh", ID = 132 },
    [150] = { name = "Cold Percht Sleigh Final", ID = 150 },
    [147] = { name = "Cold Percht Sleigh Variant", ID = 147 },
    [140] = { name = "Cony Cart", ID = 140 },
    [61] = { name = "Copper Fly", ID = 61 },
    [169] = { name = "Coral Rhea", ID = 169 },
    [79] = { name = "Coralripper", ID = 79 },
    [221] = { name = "Corpsefire Skull", ID = 221 },
    [116] = { name = "Cranium Spider", ID = 116 },
    [230] = { name = "Crimson Fang", ID = 230 },
    [33] = { name = "Crimson Ray", ID = 33 },
    [16] = { name = "Crystal Wolf", ID = 16 },
    [172] = { name = "Cunning Hyaena", ID = 172 },
    [187] = { name = "Dandelion", ID = 187 },
    [134] = { name = "Dark Percht Sleigh", ID = 134 },
    [152] = { name = "Dark Percht Sleigh Final", ID = 152 },
    [149] = { name = "Dark Percht Sleigh Variant", ID = 149 },
    [216] = { name = "Darkfire Devourer", ID = 216 },
    [166] = { name = "Dawn Strayer", ID = 166 },
    [224] = { name = "Dawnbringer Pegasus", ID = 224 },
    [41] = { name = "Desert King", ID = 41 },
    [13] = { name = "Donkey", ID = 13 },
    [219] = { name = "Doom Skull", ID = 219 },
    [53] = { name = "Doombringer", ID = 53 },
    [31] = { name = "Dragonling", ID = 31 },
    [6] = { name = "Draptor", ID = 6 },
    [104] = { name = "Dreadhare", ID = 104 },
    [20] = { name = "Dromedary", ID = 20 },
    [165] = { name = "Dusk Pryer", ID = 165 },
    [123] = { name = "Ebony Tiger", ID = 123 },
    [111] = { name = "Ember Saurian", ID = 111 },
    [191] = { name = "Emerald Raven", ID = 191 },
    [108] = { name = "Emerald Sphinx", ID = 108 },
    [70] = { name = "Emerald Waccoon", ID = 70 },
    [74] = { name = "Emperor Deer", ID = 74 },
    [154] = { name = "Ether Badger", ID = 154 },
    [170] = { name = "Eventide Nandu", ID = 170 },
    [124] = { name = "Feral Tiger", ID = 124 },
    [178] = { name = "Festive Mammoth", ID = 178 },
    [135] = { name = "Festive Snowman", ID = 135 },
    [47] = { name = "Flamesteed", ID = 47 },
    [126] = { name = "Fleeting Knowledge", ID = 126 },
    [161] = { name = "Floating Augur", ID = 161 },
    [67] = { name = "Floating Kashmir", ID = 67 },
    [159] = { name = "Floating Sage", ID = 159 },
    [160] = { name = "Floating Scholar", ID = 160 },
    [65] = { name = "Flying Divan", ID = 65 },
    [218] = { name = "Foxmouse", ID = 218 },
    [210] = { name = "Frostbringer", ID = 210 },
    [89] = { name = "Frostflare", ID = 89 },
    [201] = { name = "Giant Beaver", ID = 201 },
    [64] = { name = "Glacier Vagabond", ID = 64 },
    [228] = { name = "Glacier Wyrm", ID = 228 },
    [118] = { name = "Gloom Widow", ID = 118 },
    [190] = { name = "Gloomwurm", ID = 190 },
    [71] = { name = "Glooth Glider", ID = 71 },
    [194] = { name = "Gloothomotive", ID = 194 },
    [32] = { name = "Gnarlhound", ID = 32 },
    [107] = { name = "Gold Sphinx", ID = 107 },
    [59] = { name = "Golden Dragonfly", ID = 59 },
    [223] = { name = "Gorgon Hydra", ID = 223 },
    [81] = { name = "Gorongra", ID = 81 },
    [158] = { name = "Green Rolling Barrel", ID = 158 },
    [144] = { name = "Gryphon", ID = 144 },
    [55] = { name = "Hailstorm Fury", ID = 55 },
    [162] = { name = "Haze", ID = 162 },
    [131] = { name = "Hibernal Moth", ID = 131 },
    [63] = { name = "Highland Yak", ID = 63 },
    [177] = { name = "Holiday Mammoth", ID = 177 },
    [185] = { name = "Hyacinth", ID = 185 },
    [212] = { name = "Icebreacher", ID = 212 },
    [209] = { name = "Ink Spotted Koi", ID = 209 },
    [29] = { name = "Ironblight", ID = 29 },
    [100] = { name = "Ivory Fang", ID = 100 },
    [103] = { name = "Jackalope", ID = 103 },
    [48] = { name = "Jade Lion", ID = 48 },
    [196] = { name = "Jade Shrine", ID = 196 },
    [145] = { name = "Jousting Eagle", ID = 145 },
    [110] = { name = "Jungle Saurian", ID = 110 },
    [125] = { name = "Jungle Tiger", ID = 125 },
    [18] = { name = "Kingly Deer", ID = 18 },
    [175] = { name = "Krakoloss", ID = 175 },
    [130] = { name = "Lacewing Moth", ID = 130 },
    [27] = { name = "Lady Bug", ID = 27 },
    [112] = { name = "Lagoon Saurian", ID = 112 },
    [93] = { name = "Leafscuttler", ID = 93 },
    [66] = { name = "Magic Carpet", ID = 66 },
    [30] = { name = "Magma Crawler", ID = 30 },
    [220] = { name = "Magma Skull", ID = 220 },
    [28] = { name = "Manta Ray", ID = 28 },
    [120] = { name = "Marsh Toad", ID = 120 },
    [176] = { name = "Merry Mammoth", ID = 176 },
    [5] = { name = "Midnight Panther", ID = 5 },
    [199] = { name = "Mint ibex", ID = 199 },
    [119] = { name = "Mole", ID = 119 },
    [96] = { name = "Mould Shell", ID = 96 },
    [91] = { name = "Mouldpincer", ID = 91 },
    [136] = { name = "Muffled Snowman", ID = 136 },
    [206] = { name = "Mutated Abomination", ID = 206 },
    [222] = { name = "Mystic Jaguar", ID = 222 },
    [192] = { name = "Mystic Raven", ID = 192 },
    [98] = { name = "Neon Sparkid", ID = 98 },
    [50] = { name = "Nethersteed", ID = 50 },
    [69] = { name = "Night Waccoon", ID = 69 },
    [88] = { name = "Nightdweller", ID = 88 },
    [143] = { name = "Nightmarish Crocovile", ID = 143 },
    [85] = { name = "Nightstinger", ID = 85 },
    [40] = { name = "Noble Lion", ID = 40 },
    [82] = { name = "Noctungra", ID = 82 },
    [202] = { name = "Noxious Ripptor", ID = 202 },
    [197] = { name = "Obsidian Shrine", ID = 197 },
    [215] = { name = "Obstinate Ox", ID = 215 },
    [227] = { name = "Pegasus", ID = 227 },
    [186] = { name = "Peony", ID = 186 },
    [182] = { name = "Phant", ID = 182 },
    [167] = { name = "Phantasmal Jade", ID = 167 },
    [37] = { name = "Platesaurian", ID = 37 },
    [80] = { name = "Plumfish", ID = 80 },
    [57] = { name = "Poisonbane", ID = 57 },
    [198] = { name = "Poppy ibex", ID = 198 },
    [138] = { name = "Rabbit Rickshaw", ID = 138 },
    [2] = { name = "Racing Bird", ID = 2 },
    [193] = { name = "Radiant Raven", ID = 193 },
    [10] = { name = "Rapid Boar", ID = 10 },
    [86] = { name = "Razorcreep", ID = 86 },
    [157] = { name = "Red Rolling Barrel", ID = 157 },
    [97] = { name = "Reed Lurker", ID = 97 },
    [87] = { name = "Rift Runner", ID = 87 },
    [181] = { name = "Rift Watcher", ID = 181 },
    [68] = { name = "Ringtail Waccoon", ID = 68 },
    [141] = { name = "River Crocovile", ID = 141 },
    [180] = { name = "Rune Watcher", ID = 180 },
    [188] = { name = "Rustwurm", ID = 188 },
    [121] = { name = "Sanguine Frog", ID = 121 },
    [168] = { name = "Savanna Ostrich", ID = 168 },
    [173] = { name = "Scruffy Hyaena", ID = 173 },
    [78] = { name = "Sea Devil", ID = 78 },
    [101] = { name = "Shadow Claw", ID = 101 },
    [24] = { name = "Shadow Draptor", ID = 24 },
    [72] = { name = "Shadow Hart", ID = 72 },
    [109] = { name = "Shadow Sphinx", ID = 109 },
    [183] = { name = "Shellodon", ID = 183 },
    [42] = { name = "Shock Head", ID = 42 },
    [56] = { name = "Siegebreaker", ID = 56 },
    [83] = { name = "Silverneck", ID = 83 },
    [184] = { name = "Singeing Steed", ID = 184 },
    [226] = { name = "Skybreaker Pegasus", ID = 226 },
    [84] = { name = "Slagsnare", ID = 84 },
    [102] = { name = "Snow Pelt", ID = 102 },
    [164] = { name = "Snow Strider", ID = 164 },
    [128] = { name = "Snowy Owl", ID = 128 },
    [94] = { name = "Sparkion", ID = 94 },
    [217] = { name = "Spirit of Purity", ID = 217 },
    [11] = { name = "Stampor", ID = 11 },
    [60] = { name = "Steel Bee", ID = 60 },
    [34] = { name = "Steelbeak", ID = 34 },
    [106] = { name = "Stone Rhino", ID = 106 },
    [214] = { name = "Surly Steer", ID = 214 },
    [142] = { name = "Swamp Crocovile", ID = 142 },
    [95] = { name = "Swamp Snapper", ID = 95 },
    [19] = { name = "Tamed Panda", ID = 19 },
    [207] = { name = "Tangerine Flecked Koi", ID = 207 },
    [127] = { name = "Tawny Owl", ID = 127 },
    [51] = { name = "Tempest", ID = 51 },
    [39] = { name = "The Hellgrip", ID = 39 },
    [14] = { name = "Tiger Slug", ID = 14 },
    [8] = { name = "Tin Lizzard", ID = 8 },
    [7] = { name = "Titanica", ID = 7 },
    [195] = { name = "Topaz Shrine", ID = 195 },
    [122] = { name = "Toxic Toad", ID = 122 },
    [62] = { name = "Tundra Rambler", ID = 62 },
    [12] = { name = "Undead Cavebear", ID = 12 },
    [15] = { name = "Uniwheel", ID = 15 },
    [38] = { name = "Ursagrodon", ID = 38 },
    [179] = { name = "Void Watcher", ID = 179 },
    [171] = { name = "Voracious Hyaena", ID = 171 },
    [99] = { name = "Vortexion", ID = 99 },
    [43] = { name = "Walker", ID = 43 },
    [3] = { name = "War Bear", ID = 3 },
    [17] = { name = "War Horse", ID = 17 },
    [35] = { name = "Water Buffalo", ID = 35 },
    [174] = { name = "White Lion", ID = 174 },
    [1] = { name = "Widow Queen", ID = 1 },
    [52] = { name = "Winter King", ID = 52 },
    [211] = { name = "Winterstride", ID = 211 },
    [105] = { name = "Wolpertinger", ID = 105 },
    [54] = { name = "Woodland Prince", ID = 54 },
    [225] = { name = "Wrathfire Pegasus", ID = 225 },
    [155] = { name = "Zaoan Badger", ID = 155 }
}


local mountDoll = Action()

function mountDoll.onUse(player, item, fromPosition, target, toPosition, isHotkey)
    player:sendMountWindow(mounts)
    return true
end

mountDoll:id(mounts.dollID)
mountDoll:register()
